passthru: Add support for setting up passthru fabrics namespaces
This patch adds a PASSTHRU option to the setup_nvme and unsetup_nvme
scripts. These only work with a passthru enabled kernel which is not
yet upstream but can be enabled via patches.

diff --git a/tools/nvmeof/server/setup_nvmet b/tools/nvmeof/server/setup_nvmet
--- a/tools/nvmeof/server/setup_nvmet
+++ b/tools/nvmeof/server/setup_nvmet
@@ -22,19 +22,30 @@ OFFLOAD=${OFFLOAD:-none}
 PORT=${PORT:-4420}
 IP=${IP:-172.18.1.1}
 TRANS=${TRANS:-rdma}
+PASSTHRU=${PASSTHRU:-no}
 EXISTS=false
 
 cd $CFG/nvmet
 
-if [ ! -d subsystems/$SUBSYS ]; then
-   echo "Creating subsystem ${SUBSYS}."
-   mkdir subsystems/$SUBSYS
+if [ $PASSTHRU == "yes" ]; then
+    SUBDIR=pt
 else
-   echo "Adding ${DEV} to existing subsystem ${SUBSYS}."
+    SUBDIR=subsystems
+fi
+
+if [ ! -d ${SUBDIR}/$SUBSYS ]; then
+   echo "Creating subsystem ${SUBDIR}/${SUBSYS}."
+   mkdir ${SUBDIR}/$SUBSYS
+else
+   if [ $PASSTHRU == "yes" ]; then
+       echo "subsystem cannot already exist for passthru!"
+       exit 1
+   fi
+   echo "Adding ${DEV} to existing subsystem ${SUBDIR}/${SUBSYS}."
    EXISTS=true
 fi
 
-cd subsystems/$SUBSYS
+cd ${SUBDIR}/$SUBSYS
 if [ $EXISTS == "false" ]; then
     echo 1 > attr_allow_any_host
 
@@ -52,6 +63,10 @@ else
     cd ..
 fi
 
+if [ $PASSTHRU == "yes" ]; then
+    echo -n $DEV > attr_ctrl_path
+    echo -n 1 > attr_enable
+else
 if [ -c $DEV ]; then
     if [[ $DEV == *"nvme"* ]]; then
 	for ns in ${DEV}n*; do
@@ -80,6 +95,7 @@ else
 
     echo 1 > enable
 fi
+fi
 
 if [ $EXISTS == "true" ]; then
     exit 0
@@ -99,5 +115,5 @@ if [ $P2PMEM != "none" ]; then
     echo "Using p2p memory"
 fi
 
-ln -s $CFG/nvmet/subsystems/$SUBSYS \
-   $CFG/nvmet/ports/${PORT}/subsystems/$SUBSYS
+ln -s $CFG/nvmet/${SUBDIR}/$SUBSYS \
+    $CFG/nvmet/ports/${PORT}/subsystems/$SUBSYS
diff --git a/tools/nvmeof/server/unsetup_nvmet b/tools/nvmeof/server/unsetup_nvmet
--- a/tools/nvmeof/server/unsetup_nvmet
+++ b/tools/nvmeof/server/unsetup_nvmet
@@ -2,13 +2,28 @@
 
 CFG=${CFG:-/sys/kernel/config/nvmet/}
 SUBSYS=${SUBSYS:-eideticom}
+PASSTHRU=${PASSTHRU:-no}
 PORT=${PORT:-4420}
 
-if [ -e $CFG/subsystems/$SUBSYS/namespaces/1/enable ]; then
-    rm -f $CFG/ports/${PORT}/subsystems/$SUBSYS || true
-    echo 0 > $CFG/subsystems/$SUBSYS/namespaces/1/enable
-
-    rmdir $CFG/subsystems/$SUBSYS/namespaces/* || true
-    rmdir $CFG/subsystems/$SUBSYS || true
-    rmdir $CFG/ports/${PORT} || true
+if [ $PASSTHRU == "yes" ]; then
+    if [ -e $CFG/pt/$SUBSYS/attr_enable ]; then
+	rm -f $CFG/ports/${PORT}/subsystems/$SUBSYS || true
+	echo 0 > $CFG/pt/$SUBSYS/attr_enable
+	
+	rmdir $CFG/pt/$SUBSYS|| true
+	rmdir $CFG/ports/${PORT} || true
+    else
+	echo "could not remove passthru subsystem ${SUBSYS}."
+    fi
+else
+    if [ -e $CFG/subsystems/$SUBSYS/namespaces/1/enable ]; then
+	rm -f $CFG/ports/${PORT}/subsystems/$SUBSYS || true
+	echo 0 > $CFG/subsystems/$SUBSYS/namespaces/1/enable
+	
+	rmdir $CFG/subsystems/$SUBSYS/namespaces/* || true
+	rmdir $CFG/subsystems/$SUBSYS || true
+	rmdir $CFG/ports/${PORT} || true
+    else
+	echo "could not remove standard subsystem ${SUBSYS}."
+    fi
 fi
